
- name: Check vm {{ container_name }} exist
  shell: lxc list | grep -q {{ container_name }}
  changed_when: false
  ignore_errors: true
  register: lxc_list

- name: Create vms
  command: lxc launch ubuntu:22.04 {{ container_name }} -p {{ container_name }}
  when: lxc_list.rc != 0
  ignore_errors: true