- name: "Check htpassw"
  stat: path={{ path_to_check }}
  register: file
- name: "Request input username"
  pause:
    prompt: "Username?"
  register: username
  when: file.stat.exists == False
- name: "Request input password"
  pause:
    prompt: "Password?"
  register: password
  when: file.stat.exists == False
- name: "Request input password confirmation"
  pause:
    prompt: "Repeat password?"
  register: ask_twice
  when: file.stat.exists == False
- name: Make sure password match
  fail:
    msg: "Password Mismatch"
  when: file.stat.exists == False and password.user_input != ask_twice.user_input
