# This is the main playbook 
# ansible-playbook main-playbook.yml


---
- name: Install jdauphant.nginx on mini
  hosts: mini
  vars_prompt:
    - name: htpass_username
      prompt: "htpassw username?"
      private: no
    - name: htpass_password
      prompt: "htpassw password?"
      private: yes
    - name: htpass_ask_twice
      prompt: "Repeat htpassw password?"
      private: yes
  user: root
  pre_tasks:
    - name: Make sure password match
      fail:
        msg: "Password Mismatch"
      when: htpass_password != htpass_ask_twice
  tasks:
    - name: Make sure we can use htpasswd module
      apt: "pkg=python-passlib state=installed"
    - name: "Generate htpasswd"
      htpasswd:
        path: /etc/nginx/passwords/iu_pa.password
        name: "{{ htpass_username }}"
        password: "{{ htpass_password }}"
        owner: root
        group: www-data
        mode: 0640
  roles:
    - jdauphant.ssl-certs
    - role: jdauphant.nginx
      nginx_configs:
          ssl:
               - ssl_certificate_key {{ssl_certs_privkey_path}}
               - ssl_certificate     {{ssl_certs_cert_path}}
      nginx_sites:
          default:
               - listen 443 ssl
               - server_name _
               - root "/var/www/html"
               - index index.html
               - |
                 location / {
                     # First attempt to serve request as file, then
                     # as directory, then fall back to displaying a 404.
                     try_files $uri $uri/ =404;
                 }
               - |
                 location /qbittorrent/ {
                     proxy_pass         http://127.0.0.1:8080/;
                     auth_basic           "qbittorrent";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                 }
               - |
                 location /transmission/ {
                     proxy_pass         http://127.0.0.1:9091/transmission/;
                     proxy_pass_header X-Transmission-Session-Id;
                     auth_basic           "transmission";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                 }
               - |
                 location /rpc {
                     proxy_pass         http://127.0.0.1:9091/transmission/rpc;
                 }
               - |
                 location /pub {
                     autoindex on;
                     auth_basic "Public";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                 }



