# from galaxy
- src : https://github.com/jdauphant/ansible-role-nginx.git
  version: v2.8.1

- src: https://github.com/bertvv/ansible-role-samba.git
  name: bertvv.samba
  version: v2.3.0

- src: https://github.com/nicolasjulian/ansible-role-nginx-modsec3-crs3.git
