# This is the main playbook
# ansible-playbook main-playbook.yml

---
- include: "provisionning/nginx.yml"
- include: "provisionning/samba.yml"
- include: "provisionning/apt.yml"
- include: "provisionning/vnc.yml"
- include: "provisionning/firewall.yml"
- include: "provisionning/p2p.yml"
- include: "provisionning/fail2ban.yml"
