# This is the main playbook
# ansible-playbook main-playbook.yml

---
- include: "provisionning/ssh.yml"
- include: "provisionning/fstab.yml"
- include: "provisionning/apt.yml"
- include: "provisionning/lxd.yml"
- include: "provisionning/nginx.yml"
- include: "provisionning/certbot.yml"
- include: "provisionning/samba.yml"
- include: "provisionning/firewall.yml"
- include: "provisionning/fail2ban.yml"
- include: "provisionning/pandentia.yml"
- include: "provisionning/glances.yml"
