# This is the main playbook
# ansible-playbook main-playbook.yml

---
- include: "provisionning/ssh.yml"
- include: "provisionning/apt.yml"
- include: "provisionning/nginx.yml"
- include: "provisionning/samba.yml"
- include: "provisionning/firewall.yml"
- include: "provisionning/fail2ban.yml"
- include: "provisionning/docker.yml"
