# This is the main playbook
# ansible-playbook main-playbook.yml

---
- include: "provisionning/nginx.yml"
- include: "provisionning/samba.yml"
- include: "provisionning/apt.yml"
- include: "provisionning/vnc.yml"
