version: '3'

services:
  ansible:
    build: ./ansible/ansible-runner/
    image: ansible/ansible-runner
    network_mode: host
    working_dir: /data
    volumes:
        - $HOSTDIR/.ssh:/root/.ssh/:ro
        - $HOSTDIR$WORKSPACE:/data:rw
