version: '3'

services:
  ansible:
    build: ./ansible/ansible-runner/
    image: ansible/ansible-runner
    network_mode: host
    working_dir: /data
    volumes:
        - /home/panoi/perso/nodered/ssh:/root/.ssh/
        - /home/panoi/perso/nodered/$WORKSPACE:/data:rw
