---
- name: Get infos on container
  command: docker inspect vaultwarden
  register: vaultwarden_status
  ignore_errors: True
- name: vaultwarden
  command: sudo docker run -d --restart=unless-stopped --name="vaultwarden" -v /home/pascal/vaultwarden:/data -p 12093:80 vaultwarden/server:latest
  when: vaultwarden_status.rc == 1
