---
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: vaultwarden
    service_port: 12094
    service_ip: 127.0.0.1
    public_port: 12093
    cleanup_cmd: /usr/bin/docker rm -f vaultwarden
    startup_cmd: /usr/bin/docker run -i --name="vaultwarden" -v /home/pascal/vaultwarden:/data -p 12094:80 vaultwarden/server:latest