---
- name: Get infos on container
  command: docker inspect blog
  register: blog_status
  ignore_errors: True
- name: blog
  command: sudo docker run --name=blog -v /home/pascal/blog/.ghost_private.json:/var/www/.ghost.json --restart=unless-stopped -p 9913:8000 netpascal0123/gatsby-starter-ghostedmediawiki:latest
  when: blog_status.rc == 1
