---
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: dashkiosk
    service_port: 11630
    service_ip: 127.0.0.1
    public_port: 11631
    cleanup_cmd: /usr/bin/docker rm -f dashkiosk
    startup_cmd: /usr/bin/docker run -i --name=dashkiosk --net=host  -v /home/pascal/dashkiosk:/database  -e "port=11630"  vincentbernat/dashkiosk:latest