---
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: drawio
    service_port: 13622
    service_ip: 127.0.0.1
    public_port: 13621
    cleanup_cmd: /usr/bin/docker rm -f drawio
    startup_cmd: /usr/bin/docker run -i -e PUBLIC_DNS=drawio.netpascal.site  --name=drawio -p 13622:8080 jgraph/drawio