---
- name: Get infos on container
  command: docker inspect gateone
  register: gateone_status
  ignore_errors: True
- name: Gateone
  command: docker create --restart=unless-stopped --name=gateone --network=bridge -p 8000:8000 netpascal0123/ranger:gateone --log_file_prefix=/gateone/logs/gateone.log --url_prefix=/gate --origins=gate.netpascal.site
  when: gateone_status.rc == 1
