---
- name: Get infos on container
  command: docker inspect gogs
  register: gogs_status
  ignore_errors: True
- name: Ensures /home/pascal/gitea/gitea/conf dir exists
  file: path=/home/pascal/gitea/gitea/conf state=directory
- name: copy gogs config
  template: src=git.ini dest=/home/pascal/gitea/gitea/conf/app.ini owner=1000 group=1000 mode=0644
  when: gogs_status.rc == 1
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: gogs
    service_port: 10081
    service_ip: 127.0.0.1
    public_port: 10080
    cleanup_cmd: /usr/bin/docker rm -f gogs
    startup_cmd: /usr/bin/docker run -i --name=gogs  -e USER_UID=1000 -e USER_GID=1000 -p 10022:22 -p 10081:3000 -v /home/pascal/gitea:/data gitea/gitea:latest

