
---
- name: Get infos on container
  command: docker inspect gpodder_app_1
  register: gpodder_status
  ignore_errors: True
- name: Ensures /home/pascal/gpodder/ dir exists
  file: path=/home/pascal/gpodder/postgres_init state=directory
  when: gpodder_status.rc == 1
- name: Template of gpodder docker-compose
  template:
    src: gpodder.yml
    dest: /home/pascal/gpodder/docker-compose.yml
  when: gpodder_status.rc == 1
- name: Template of gpodder postgres_init
  template:
    src: gpodder/setup_mygpo.sh
    dest: /home/pascal/gpodder/postgres_init/setup_mygpo.sh
  when: gpodder_status.rc == 1
- name: Generate gpodder SECRET_KEY
  shell: echo SECRET_KEY=`openssl rand -hex 16` > /home/pascal/gpodder/.env 
  when: gpodder_status.rc == 1
- name: Generate gpodder POSTGRES_PASSWORD
  shell: echo POSTGRES_PASSWORD=`openssl rand -hex 16` >> /home/pascal/gpodder/.env 
  when: gpodder_status.rc == 1
- name: Create gpodder server container
  command: docker-compose up -d
  args:
    chdir: /home/pascal/gpodder/
  when: gpodder_status.rc == 1
- name: Init gpodder migrate
  command: docker-compose exec app python manage.py migrate
  args:
    chdir: /home/pascal/gpodder/
  when: gpodder_status.rc == 1
- name: Init gpodder collectstatic
  command: docker-compose exec app python manage.py collectstatic
  args:
    chdir: /home/pascal/gpodder/
  when: gpodder_status.rc == 1
- name: Init gpodder restart celery now db is ready
  command: docker-compose restart beat worker
  args:
    chdir: /home/pascal/gpodder/
  when: gpodder_status.rc == 1
- name: Init gpodder remerber to createsuperuser manually
  command: echo docker-compose exec app python manage.py createsuperuser
  when: gpodder_status.rc == 1
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: gpodder
    service_port: 5638
    service_ip: 127.0.0.1
    public_port: 5640
    cleanup_cmd: /usr/bin/docker-compose stop
    startup_cmd: /usr/bin/docker-compose up