---
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: grocy
    service_port: 24102
    service_ip: 127.0.0.1
    public_port: 24103
    cleanup_cmd: /usr/bin/docker rm -f grocy
    startup_cmd: /usr/bin/docker run --name=grocy -p 24102:80 -i -v /home/pascal/grocy/:/config/ -e PUID=1000 -e PGID=1000 -e TZ=Europe/Paris  lscr.io/linuxserver/grocy