---
- name: Get infos on container
  command: docker inspect home-assistant
  register: hass_status
  ignore_errors: True
- git:
    repo: 'https://github.com/PascalNoisette/homeassistant-config.git'
    dest: /home/pascal/home-assistant-cfg
  when: hass_status.rc == 1
- name: Home Assistant
  command: docker run  -d --name="home-assistant" -e "TZ=Europe/Paris" --restart=unless-stopped --device /dev/ttyUSB0:/dev/ttyUSB0 --device /dev/ttyACM0:/dev/ttyACM0  -v /home/pascal/stick:/stick -v /home/pascal/home-assistant-cfg:/config --net=host homeassistant/home-assistant:stable
  when: hass_status.rc == 1
- name: Upgrade the container I dont want to create my own image...
  command: sudo docker exec -it home-assistant apk add cups
  when: hass_status.rc == 1
- name: Home Assistant
  command: docker run  -d --name="velo" -p8124:8123 -e "TZ=Europe/Paris" --restart=unless-stopped -v /home/pascal/home-assistant-cfg-velo/:/config homeassistant/home-assistant:stable
  when: hass_status.rc == 1
