---
- name: Home Assistant
  command: docker run  -d --name="home-assistant" -e "TZ=Europe/Paris" --restart=unless-stopped --privileged --device /dev/ttyUSB0:/dev/ttyUSB0 --device /dev/ttyACM0:/dev/ttyACM0 -v /run/dbus:/run/dbus:ro  -v /home/pascal/home-assistant-cfg:/config --net=host ghcr.io/home-assistant/home-assistant:stable
