---
- name: Ensures /home/pascal/hivemqtt/ dir exists
  file: path=/home/pascal/hivemqtt/ state=directory
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: hivemqtt
    service_port: 30804
    service_ip: 127.0.0.1
    public_port: 30805
    cleanup_cmd: /usr/bin/docker rm -f hivemqtt
    startup_cmd: /usr/bin/docker run -i --name=hivemqtt -p 30804:8080 -p 1884:1883 hivemq/hivemq-ce
- name: Create second hivemqtt socket activated service
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system/{{ name }}second-{{ item | basename | replace('.j2','')  }}
  with_fileglob:
  - provisionning/templates/socket_activated/systemctl/proxy*
  vars:
    name: hivemqtt
    service_port: 1884
    service_ip: 127.0.0.1
    wait_cmd: /usr/local/bin/waitport
    public_port: 1883
- name: Enable hivemqtt second proxy service
  command: systemctl enable hivemqttsecond-proxy.socket
- name: Start second hivemqtt proxy towards service
  command: systemctl start hivemqttsecond-proxy.socket
