---
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: jellyfin
    service_port: 8096
    service_ip: 127.0.0.1
    public_port: 8097
    cleanup_cmd: /usr/bin/docker rm -f jellyfin
    startup_cmd: /usr/bin/docker run -i --name=jellyfin --privileged  -v /media/truite/Ebook/:/data/ebooks -v /media/truite/Serie/:/data/tvshows -v /media/Hermit/Film/:/data/movies -v /media/data/jellyfin:/config  -e JELLYFIN_PublishedServerUrl=https://jellyfin.netpascal.site/ -e TZ='Europe/Paris' --net=host linuxserver/jellyfin
