---
- name: Get infos on container
  command: docker inspect nodered
  register: genghistask_status
  ignore_errors: True
- name: Nodered start
  command: docker run -d --name nodered --restart=unless-stopped -p8082:1880 -e HOSTDIR=/home/pascal/nodered -v /home/pascal/node_red:/data -v /home/pascal/node_red/.ssh:/usr/src/node-red/.ssh -v /var/run/docker.sock:/var/run/docker.sock nodered/node-red
  when: genghistask_status.rc == 1
- name: Add docker client
  shell: echo "apk add --update --no-cache docker-cli  docker-compose shadow" | docker exec -uroot -i nodered sh
- name: Get docker group ID
  shell: "grep docker /etc/group | cut -d : -f 3"
  register: docker_gid
#- name: Move gid taken by someone else
#  shell: groupmod -g 998 ping
- name: Add docker user
  shell: docker exec -uroot nodered addgroup docker -g {{ docker_gid.stdout }}
- name: Add docker group
  command: docker exec -uroot nodered addgroup node-red docker
- name: Restart to apply docker user permission
  command: docker restart nodered

