---
- name: Get infos on container
  command: docker inspect genghis
  register: genghistask_status
  ignore_errors: True
- name: Nodered
  command: docker run -d --name nodered    --restart=unless-stopped -p8082:1880 -v /home/pascal/node_red:/data -v /home/pascal/node_red/.ssh:/usr/src/node-red/.ssh -v /var/run/docker.sock:/var/run/docker.sock nodered/node-red
  when: genghistask_status.rc == 1
