---
- name: Get infos on container
  command: docker inspect genghistask
  register: genghistask_status
  ignore_errors: True
- name: Genghistask
  command: docker run -d --name genghis    --restart=unless-stopped -p8081:3000 -v /home/pascal/genghis/.ssh:/root/.ssh -v /var/run/docker.sock:/var/run/docker.sock -e GIT_BRANCH=master -e GIT_REPO='ssh://git@gitlab.com/PascalNoisette/greasemonkey.git' genghistask/ui:1.5
  when: genghistask_status.rc == 1
