---
- name: Get infos on container
  command: docker inspect jet
  register: jet_status
  ignore_errors: True
- include: tasks/request_credential.yml path_to_check=/tmp/always_check
  when: jet_status.rc == 1
- name: Jet
  command: docker run --name=jet --network=bridge -p 9123:9123 --restart=unless-stopped --detach=true netpascal0123/ranger:jet
  when: jet_status.rc == 1
