---
- name: Get infos on container
  command: docker inspect joplin_server_1
  register: joplin_status
  ignore_errors: True
- name: Ensures /tmp/joplin/ dir exists
  file: path=/tmp/joplin/ state=directory
  when: joplin_status.rc == 1
- name: Template of docker-compose
  template:
    src: joplin.yml.j2
    dest: /tmp/joplin/docker-compose.yml
  when: joplin_status.rc == 1
- name: Create joplin server container
  command: docker-compose up -d server
  args:
    chdir: /tmp/joplin/
  when: joplin_status.rc == 1
- name: Retrieve web token from the sqlite to .env
  command: echo -n 'JOPLIN_WEBCLIPPER_TOKEN='> .env; echo 'select value from settings where key="api.token"' | docker run -i --rm -v /home/pascal/joplin:/data sstc/sqlite3 sqlite3 database.sqlite >> .env
  args:
    chdir: /tmp/joplin/
  when: joplin_status.rc == 1
- name: Create joplin web container
  command: docker-compose up -d web
  args:
    chdir: /tmp/joplin/
  when: joplin_status.rc == 1

