---
- name: Get infos on container
  command: docker inspect lxdui
  register: lxdui_status
  ignore_errors: True
- name: Lxd UI Container
  command: sudo docker create --name=lxdui -it -p 15151:15151 -v /var/snap/lxd/common/lxd/unix.socket:/var/snap/lxd/common/lxd/unix.socket netpascal0123/lxdui
  when: lxdui_status.rc == 1
