---
- name: Get infos on container
  command: docker inspect miniflux_miniflux_1
  register: miniflux_status
  ignore_errors: True
- name: Remove file
  file:
    path: /tmp/miniflux
    state: absent
  when: miniflux_status.rc == 1
- git:
    repo: 'https://github.com/PascalNoisette/miniflux.git'
    dest: /tmp/miniflux
  when: miniflux_status.rc == 1
- name: Create and start services of miniflux container
  docker_service:
    project_src: /tmp/miniflux
    services: "db"
  when: miniflux_status.rc == 1
- name: Wait 30 seconds
  wait_for_connection:
    timeout: 15
    delay: 15
  when: miniflux_status.rc == 1
- name: Setup miniflux
  docker_service:
    project_src: /tmp/miniflux
    services: "setup"
  when: miniflux_status.rc == 1
- name: Wait 30 seconds
  wait_for_connection:
    timeout: 15
    delay: 15
  when: miniflux_status.rc == 1
- name: Finish setup 
  docker_service:
    services: "setup"
    project_src: /tmp/miniflux
    state: absent
  when: miniflux_status.rc == 1
- name: Create miniflux container
  docker_service:
    project_src: /tmp/miniflux
    services: "miniflux"
  register: miniflux_status
  when: miniflux_status.rc == 1
