---
- name: Get infos on container
  command: docker inspect miniflux_miniflux_1
  register: miniflux_status
  ignore_errors: True
- name: Remove file
  file:
    path: /tmp/miniflux
    state: absent
  when: miniflux_status.rc == 1
- git:
    repo: 'https://github.com/PascalNoisette/miniflux.git'
    dest: /tmp/miniflux
  when: miniflux_status.rc == 1
- name: Create and start services of miniflux container
  command: docker-compose up -d db
  args:
    chdir: /tmp/miniflux
  when: miniflux_status.rc == 1
- name: PhpMyAdmin (adminer)
  command: docker create --name=miniflux_adminer --network=miniflux_default -p 11111:8080 adminer
  when: miniflux_status.rc == 1
- name: Wait 30 seconds
  wait_for_connection:
    timeout: 15
    delay: 15
  when: miniflux_status.rc == 1
- name: Setup miniflux
  command: docker-compose up -d setup
  args:
    chdir: /tmp/miniflux
  when: miniflux_status.rc == 1
- name: Wait 30 seconds
  wait_for_connection:
    timeout: 15
    delay: 15
  when: miniflux_status.rc == 1
- name: Finish setup 
  command: docker-compose rm -f setup
  args:
    chdir: /tmp/miniflux
  when: miniflux_status.rc == 1
- name: Create miniflux container
  command: docker-compose up -d miniflux
  args:
    chdir: /tmp/miniflux
  when: miniflux_status.rc == 1
- name: Template of docker-compose
  template:
    src: miniflux.yml.j2
    dest: /home/pascal/miniflux/docker-compose.yml
  when: miniflux.rc == 1
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: miniflux
    service_port: 3355
    service_ip: 127.0.0.1
    public_port: 3356
    wait_cmd: /usr/local/bin/waitport
    cleanup_cmd: /usr/bin/docker-compose stop
    startup_cmd: /usr/bin/docker-compose up