
---
- git:
    repo: 'https://github.com/PascalNoisette/mkdocs.git'
    dest: /home/pascal/mkdocs
- name: Ensures /home/pascal/mkdocs/site exists
  file: path=/home/pascal/mkdocs/site    state=directory owner=1000 group=1000
- name: Give permissions to doc dir
  ansible.builtin.file:
    path: /home/pascal/mkdocs/docs
    owner: 1000
    group: 1000
    recurse: yes
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: mkdocs
    service_port: 3031
    service_ip: 127.0.0.1
    public_port: 3030
    cleanup_cmd: /usr/bin/docker-compose stop
    startup_cmd: /usr/bin/docker-compose up
- name: Create vscode socket activated service
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system/vscode-{{ item | basename | replace('.j2','')  }}
  with_fileglob:
  - provisionning/templates/socket_activated/systemctl/proxy*
  vars:
    name: mkdocs
    service_port: 3033
    service_ip: 127.0.0.1
    public_port: 3032
- name: Enable vscode proxy service
  command: systemctl enable vscode-proxy.socket
- name: Start vscode proxy towards service
  command: systemctl start vscode-proxy.socket
- name: Create leanote socket activated service
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system/leanote-{{ item | basename | replace('.j2','')  }}
  with_fileglob:
  - provisionning/templates/socket_activated/systemctl/proxy*
  vars:
    name: mkdocs
    service_port: 3000
    service_ip: 127.0.0.1
    public_port: 3001
- name: Enable leanote second proxy service
  command: systemctl enable leanote-proxy.socket
- name: Start second leanote proxy towards service
  command: systemctl start leanote-proxy.socket