---
- name: Get infos on container
  command: docker inspect netboot
  register: netboot_status
  ignore_errors: True
- name: netboot
  command: sudo docker run --rm -d --name=netboot -v /media/Saumon/Logiciel/NETBOOT:/assets -p 80:80 -p 3000:3000  -p 69:69/udp  ghcr.io/netbootxyz/netbootxyz
  when: netboot_status.rc == 1
