---
- name: Get infos on container
  command: docker inspect nextcloud
  register: nextcloud_status
  ignore_errors: True
- name: Nextcloud
  command: docker run --name=nextcloud  -p 9003:80 -v /home/pascal/nextcloud:/var/www/html --restart=unless-stopped -d nextcloud
  when: nextcloud_status.rc == 1
- name: Nextcloud Install
  command: docker exec  --user www-data nextcloud php occ  maintenance:install  --database sqlite  --admin-user "admin" --admin-pass "password"
  when: nextcloud_status.rc == 1
- name: Nextcloud config trusted domains
  command: docker exec  --user www-data nextcloud php occ config:system:set trusted_domains 2 --value=netpascal.myvnc.com
  when: nextcloud_status.rc == 1
- name: Nextcloud config protocol
  command: docker exec  --user www-data nextcloud php occ config:system:set --type string --value https overwriteprotocol
  when: nextcloud_status.rc == 1
- name: Nextcloud config root
  command: docker exec  --user www-data nextcloud php occ config:system:set --type string --value /nextcloud overwritewebroot
  when: nextcloud_status.rc == 1
- name: Nextcloud config host
  command: docker exec  --user www-data nextcloud php occ config:system:set --type string --value netpascal.myvnc.com overwritehost
  when: nextcloud_status.rc == 1
- name: Nextcloud config App store
  command: docker exec  --user www-data nextcloud php occ config:system:set --type boolean --value true appstoreenabled
  when: nextcloud_status.rc == 1
