---
- name: Get infos on container
  command: docker inspect nextcloud_test
  register: nextcloud_status
  ignore_errors: True
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: nextcloud
    service_port: 9004
    service_ip: 127.0.0.1
    public_port: 9003
    cleanup_cmd: /usr/bin/docker rm -f nextcloud
    startup_cmd: /usr/bin/docker run --name=nextcloud -i -p 9004:80  -v /media/truite/Musique/:/media/Musique:ro  -v /media/truite/Shared/:/media/Shared  lscr.io/linuxserver/nextcloud
- name: Nextcloud
  command: /usr/bin/systemctl start nextcloud-docker.service
  when: nextcloud_status.rc == 1
- name: Wait 30 seconds
  wait_for_connection:
    timeout: 15
    delay: 15
  when: nextcloud_status.rc == 1
- name: Nextcloud config trusted domains
  command: docker exec nextcloud php occ config:system:set trusted_domains 2 --value=nextcloud.netpascal.click
  when: nextcloud_status.rc == 1
- name: Nextcloud config protocol
  command: docker exec nextcloud php occ config:system:set --type string --value https overwriteprotocol
  when: nextcloud_status.rc == 1
- name: Nextcloud config host
  command: docker exec nextcloud php occ config:system:set --type string --value nextcloud.netpascal.click overwritehost
  when: nextcloud_status.rc == 1
- name: Nextcloud config App store
  command: docker exec nextcloud php occ config:system:set --type boolean --value true appstoreenabled
  when: nextcloud_status.rc == 1
