---
- name: Get infos on container
  command: docker inspect nextcloud
  register: nextcloud_status
  ignore_errors: True
- name: Nextcloud
  command: docker run --name=nextcloud  -p 9003:80 -v /home/pascal/nextcloud:/var/www/html --restart=unless-stopped -d nextcloud
  when: nextcloud_status.rc == 1
- name: Nextcloud config
  command: docker exec  --user www-data nextcloud php occ config:system:set trusted_domains 2 --value=netpascal.myvnc.com
  when: nextcloud_status.rc == 1
