---
- name: Ensures /home/pascal/photoprism exists
  file: path=/home/pascal/photoprism  state=directory owner=1000 group=1000
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: photoprism
    service_port: 2342
    service_ip: 127.0.0.1
    public_port: 2343
    cleanup_cmd: /usr/bin/docker rm -f photoprism
    startup_cmd: /usr/bin/docker run --name photoprism   --security-opt seccomp=unconfined --security-opt apparmor=unconfined -p 2342:2342 -e PHOTOPRISM_UPLOAD_NSFW="true" -e PHOTOPRISM_READONLY="true" -e PHOTOPRISM_ADMIN_PASSWORD="changeme" -v /media/truite/Sauvegarde2023/photoprism:/photoprism/storage -v /media/truite/Image/:/photoprism/originals:ro photoprism/photoprism
