---
- name: Get infos on container
  command: docker inspect plex
  register: plex_status
  ignore_errors: True
- name: plex
  command: sudo docker create --privileged  --name=plex --net=host  -e VERSION=docker -v /home/pascal/plex/config:/config -v /home/pascal/plex/data:/data   --restart unless-stopped  linuxserver/plex
  when: plex_status.rc == 1
