---
- name: Get infos on container
  command: docker inspect portainer
  register: portainer_status
  ignore_errors: True
- name: Portainer
  command: docker run --name=portainer --volume="/var/run/docker.sock:/var/run/docker.sock" -e AGENT_SECRET=X -p 9000:9000 --restart=unless-stopped --detach=true portainer/portainer-ce -H unix:///var/run/docker.sock
  when: portainer_status.rc == 1
