---
- hosts: all
  become: true
  tasks:
    - name: return motd to registered var
      command: docker run --name=portainer --volume="/var/run/docker.sock:/var/run/docker.sock" -p 9000:9000 --restart=unless-stopped --detach=true portainer/portainer --no-auth
