-
- name: Get infos on container
  command: docker inspect pyload
  register: pyload_status
  ignore_errors: True
- name: pyload
  command: docker run -d -p8046:8000 -p7227:7227 -p9666:9666 --name pyload --restart unless-stopped -v /home/pascal/JDownloader/pyload:/config -v /home/pascal/Downloads:/downloads ghcr.io/linuxserver/pyload
  when: pyload_status.rc == 1
