---
- name: Ensures /home/pascal/qbit/config/ dir exists
  file: path=/home/pascal/qbit/config/ state=directory
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: qbit
    service_port: 10332
    service_ip: 127.0.0.1
    public_port: 10331
    cleanup_cmd: /usr/bin/docker rm -f qbit
    startup_cmd: /usr/bin/docker run --name qbit -v /home/pascal/qbit/config:/config -v /media/data/qbit/:/downloads -p 6881:6881 -p 6881:6881/udp -p 10332:8080  linuxserver/qbittorrent
