---
- name: Ensures /home/pascal/redash/ dir exists
  file: path=/home/pascal/redash/ state=directory
- name: install packages
  apt: pkg={{item}} state=present
  with_items: [pwgen]
- name: Generate uniq config file
  shell: |
    cd /home/pascal/redash/
    COOKIE_SECRET=$(pwgen -1s 32)
    SECRET_KEY=$(pwgen -1s 32)
    POSTGRES_PASSWORD=$(pwgen -1s 32)
    REDASH_DATABASE_URL="postgresql://postgres:${POSTGRES_PASSWORD}@postgres/postgres"
    echo "PYTHONUNBUFFERED=0" >> env
    echo "REDASH_LOG_LEVEL=INFO" >> env
    echo "REDASH_REDIS_URL=redis://redis:6379/0" >> env
    echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> env
    echo "REDASH_COOKIE_SECRET=$COOKIE_SECRET" >> env
    echo "REDASH_SECRET_KEY=$SECRET_KEY" >> env
    echo "REDASH_DATABASE_URL=$REDASH_DATABASE_URL" >> env

- name: Template of redash docker-compose
  template:
    src: redash.yml
    dest: /home/pascal/redash/docker-compose.yml
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: redash
    service_port: 7118
    service_ip: 127.0.0.1
    public_port: 7119
    cleanup_cmd: /usr/bin/docker-compose down
    startup_cmd: /usr/bin/docker-compose up
- name: botpress install
  command: sudo docker-compose run --rm server create_db
  chdir: /home/pascal/redash/