---
- name: Get infos on container
  command: docker inspect registry_registry_1
  register: registry_status
  ignore_errors: True
- name: Ensures /home/pascal/registry/ dir exists
  file: path=/home/pascal/registry/  state=directory
  when: registry_status.rc == 1
- name: Template of docker-compose
  template:
    src: registry.yml.j2
    dest: /home/pascal/registry/docker-compose.yml
  when: registry_status.rc == 1
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: registry
    service_port: 9038
    service_ip: 127.0.0.1
    public_port: 9037
    cleanup_cmd: /usr/bin/docker-compose stop
    startup_cmd: /usr/bin/docker-compose up
  
