---
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: rssbridge
    service_port: 3008
    service_ip: 127.0.0.1
    public_port: 3007
    cleanup_cmd: /usr/bin/docker rm -f rssbridge
    startup_cmd: /usr/bin/docker run -i --name=rssbridge -p 3008:80 rssbridge/rss-bridge:latest