---
- name: Get infos on container
  command: docker inspect samba
  register: samba_status
  ignore_errors: True
- name: Open Samba 
  command: sudo docker run -d --restart=unless-stopped --name samba --net=host -e USERID=1000  -e GROUPID=1000 -v /media/data/:/media/data/  dperson/samba -u "admin;password" -s "Chest;/media/data/;no;no;no;admin" -n
  when: samba_status.rc == 1
