---
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: snapdrop
    service_port: 17466
    service_ip: 127.0.0.1
    public_port: 17465
    cleanup_cmd: /usr/bin/docker rm -f snapdrop
    startup_cmd: /usr/bin/docker run -i --name=snapdrop -p 17466:80  ghcr.io/linuxserver/snapdrop
