---
- name: Get infos on container
  command: docker inspect vnc
  register: vnc_status
  ignore_errors: True
- name: vnc
  command: sudo podman run -d --restart=unless-stopped --name="vnc"  --tmpfs /run --tmpfs /run/lock --tmpfs /tmp   --cap-add SYS_BOOT --cap-add SYS_ADMIN -v /media/:/media/  -v /home/pascal/vnc/passwd:/home/default/.vnc/passwd -v /sys/fs/cgroup:/sys/fs/cgroup   -p 5902:5901 -p 6902:6901  docker.io/darkdragon001/ubuntu-gnome-vnc
  when: vnc_status.rc == 1
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: vnc
    service_port: 6902
    service_ip: 127.0.0.1
    public_port: 6901
    cleanup_cmd: /usr/bin/podman stop vnc
    startup_cmd: /usr/bin/podman start -a vnc
- name: Create alternate socket activated service
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system/{{ name }}alt-{{ item | basename | replace('.j2','')  }}
  with_fileglob:
  - provisionning/templates/socket_activated/systemctl/proxy*
  vars:
    name: vnc
    service_port: 5902
    service_ip: 127.0.0.1
    public_port: 5901
- name: Enable vnc alt proxy service
  command: systemctl enable vncalt-proxy.socket
- name: Start alt vnc proxy towards service
  command: systemctl start vncalt-proxy.socket