---
- name: Get infos on container
  command: docker inspect vnc
  register: vnc_status
  ignore_errors: True
- name: vnc
  command: sudo docker run -d --restart=unless-stopped --name="vnc"  --tmpfs /run --tmpfs /run/lock --tmpfs /tmp   --cap-add SYS_BOOT --cap-add SYS_ADMIN -v /home/pascal/Downloads:/home/default/Downloads -v /home/pascal/vnc/passwd:/home/default/.vnc/passwd -v /sys/fs/cgroup:/sys/fs/cgroup   -p 5901:5901 -p 6901:6901   darkdragon001/ubuntu-gnome-vnc
  when: vnc_status.rc == 1
