---
- name: Get infos on container
  command: docker inspect wallabag
  register: wallabag_status
  ignore_errors: True
- name: Ensures /tmp/wallabag/ dir exists
  file: path=/tmp/wallabag/ state=directory
  when: wallabag_status.rc == 1
- name: Ensures /home/pascal/wallabag/ dir exists
  file: path=/home/pascal/wallabag/ state=directory
  when: wallabag_status.rc == 1
- name: Template of docker-compose
  template:
    src: wallabag.yml.j2
    dest: /tmp/wallabag/docker-compose.yml
  when: wallabag_status.rc == 1
- name: Create wallabag server container
  command: docker-compose up -d
  args:
    chdir: /tmp/wallabag/
  when: wallabag_status.rc == 1

