---
- name: Ensures /home/pascal/wekan exists
  file: path=/home/pascal/wekan    state=directory owner=999 group=999
- name: Download docker-compose.yml
  get_url: url="https://github.com/wekan/wekan/raw/master/docker-compose.yml" dest="/home/pascal/wekan/docker-compose.yml"
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: wekan
    service_port: 80
    service_ip: 127.0.0.1
    public_port: 81
    cleanup_cmd: /usr/bin/docker compose down
    startup_cmd: /usr/bin/docker compose up
