---
- name: Get infos on container
  command: docker inspect wiki_wiki_1
  register: wiki_status
  ignore_errors: True
- name: Ensures /home/pascal/wiki/ dir exists
  file: path=/home/pascal/wiki/  state=directory
  when: wiki_status.rc == 1
- name: Template of docker-compose
  template:
    src: wiki.yml.j2
    dest: /home/pascal/wiki/docker-compose.yml
  when: wiki_status.rc == 1
- name: Create wiki server container
  command: docker-compose up -d
  args:
    chdir: /home/pascal/wiki/
  when: wiki_status.rc == 1
- include: provisionning/tasks/socket_activated_service.yml
  vars:
    name: wiki
    service_port: 10024
    service_ip: 127.0.0.1
    public_port: 10023
    cleanup_cmd: /usr/bin/docker-compose stop
    startup_cmd: /usr/bin/docker-compose up
- name: Upgrade the container I dont want to create my own image...
  command: sudo docker exec -it wiki_wiki_1 apt update
- name: Upgrade the container I dont want to create my own image...
  command: sudo docker exec -it wiki_wiki_1 mkdir /usr/share/man/man1/
  when: wiki_status.rc == 1
- name: Upgrade the container I dont want to create my own image...
  command: sudo docker exec -it wiki_wiki_1 apt install -y default-jre graphviz lilypond fluidsynth ffmpeg
  when: wiki_status.rc == 1
- name: Upgrade the container I dont want to create my own image...
  command: sudo docker exec -it wiki_wiki_1 docker-php-ext-install exif
  when: wiki_status.rc == 1



