---
- name: Get infos on container
  command: docker inspect wiki
  register: wiki_status
  ignore_errors: True
- name: Create and start services of wiki container
  command: sudo sudo docker run --name wiki -p 10023:80 -v /home/pascal/wiki/extra-php.ini:/usr/local/etc/php/conf.d/extra-php.ini -v /home/pascal/wiki/extensions:/var/www/html/extensions -v /home/pascal/wiki/LocalSettings.php:/var/www/html/LocalSettings.php:rw -v /home/pascal/wiki/images:/var/www/html/images:rw -v /home/pascal/wiki/data:/var/www/data:rw  -d mediawiki
  when: wiki_status.rc == 1
  
