---
- name: Get infos on container
  command: docker inspect wiki
  register: wiki_status
  ignore_errors: True
- name: Create and start services of wiki container
  command: sudo docker run --name wiki -p 10023:80 -v /media/Saumon/Sauvegarde/wiki/:/data:rw -d mediawiki
  when: wiki_status.rc == 1
  
