---
- name: Get infos on container
  command: docker inspect wiki
  register: wiki_status
  ignore_errors: True
- name: Create and start services of wiki container
  command: sudo docker run -d --name=wiki -p 10024:443 -p 10023:80 -v /home/pascal/bluespice/:/data -e "bs_lang=en" -e "bs_url=https://bluespice.netpascal.site/" bluespice/bluespice-free
  when: wiki_status.rc == 1
  
