---
# preload
- hosts:
    - mini
  become: yes
  gather_facts: False
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y -qq update && DEBIAN_FRONTEND=noninteractive apt install -y -q --option \"Dpkg::Options::=--force-confold\" python-minimal)

- name: Install custom packages on mini
  hosts: mini
  become: yes
  tasks:
    - name: install packages
      apt: pkg={{item}} state=present
      with_items: [vim, htop, git]
    - name: Enable universe repository
      command: add-apt-repository universe
      when: ansible_distribution == 'Ubuntu'

