---
# preload
- hosts:
    - mini
  become: yes
  gather_facts: False
  pre_tasks:
    - raw: test -e /usr/bin/python || test -e /usr/bin/python3 || (apt -y -qq update && DEBIAN_FRONTEND=noninteractive apt install -y -q --option \"Dpkg::Options::=--force-confold\" python3-minimal)

- name: Install custom packages on mini
  hosts: mini
  become: yes
  tasks:
    - name: install packages
      apt: pkg={{item}} state=present
      with_items: [vim, htop, git, curl, nethogs]
    - name: Enable universe repository
      command: add-apt-repository -y universe
      when: ansible_distribution == 'Ubuntu'

