---
# preload
- hosts:
    - mini
  become: yes
  gather_facts: False
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y -qq update && apt install -y -qq python-minimal)

- name: Install custom packages on mini
  hosts: mini
  become: yes
  tasks:
    - name: install packages
      apt: pkg={{item}} state=present
      with_items: [vim, xscreensaver, thunar, htop]
