---
- name: Install certbot packages on mini
  hosts: mini
  become: yes
  tasks:
    - name: install certbot packages
      apt: pkg={{item}} state=present
      with_items: [certbot, python3-certbot-nginx, python3-certbot-dns-ovh]
#    - name: generate cert
#      command: sudo certbot -d "*.netpascal.click" -d "netpascal.click" --dns-ovh --dns-ovh-credentials /home/pascal/ovh.ini certonly