###########################################################################################################################
# DO Community Playbooks
# Playbook: Installing Docker and Creating Containers on Ubuntu 18.04
# Based on: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04
# Guide: https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-18-04
###########################################################################################################################

#---
#- hosts: all
#  become: true
#  vars:
#    create_containers: 4
#    default_container_name: docker
#    default_container_image: ubuntu
#    default_container_command: sleep 1d
#
#  tasks:
#    - include: "{{ item }}"
#      with_fileglob:
#        - docker/*.yml


---
- hosts: first
  become: true
  vars:
    create_containers: 4
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1d
  tasks:
    - include: "docker/glances.yml"
    - include: "docker/portainer.yml"
    - include: "docker/rssbridge.yml"
    - include: "docker/jenkins.yml"
    - include: "docker/miniflux.yml"
    - include: "docker/redmine.yml"
    - include: "docker/drawio.yml"
    - include: "docker/snapdrop.yml"
    - include: "docker/circuitjs.yml"
    - include: "docker/jupiter.yml"
    - include: "docker/vscode.yml"
    - include: "docker/grocy.yml"
    - include: "docker/megamenu.yml"
    - include: "docker/gogs.yml"
    - include: "docker/wallabag.yml"
    - include: "docker/bitwardenrs.yml"
    - include: "docker/registry.yml"
    - include: "docker/cachet.yml"

###########################################################################################################################
# DO Community Playbooks
# Playbook: Installing Docker and Creating Containers on Ubuntu 18.04
# Based on: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04
# Guide: https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-18-04
###########################################################################################################################

- hosts: second
  become: true
  vars:
    create_containers: 4
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1d
  tasks:
    - include: "docker/glances.yml"
    - include: "docker/portainer_agent.yml"
    - include: "docker/mkdocs.yml"

#- hosts: jitsi
#  become: true
#  vars:
#    create_containers: 4
#    default_container_name: docker
#    default_container_image: ubuntu
#    default_container_command: sleep 1d

#  tasks:
#    - include: "docker/jitsi.yml"
#    - include: "docker/glances.yml"
#    - include: "docker/portainer_agent.yml"


#- hosts: mailu
#  become: true
#  vars:
#    create_containers: 4
#    default_container_name: docker
#    default_container_image: ubuntu
#    default_container_command: sleep 1d

#  tasks:
#    - include: "docker/mailu.yml"
#    - include: "docker/glances.yml"
#    - include: "docker/portainer_agent.yml"


- hosts: hass
  become: true
  vars:
    create_containers: 4
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1d

  tasks:
    - include: "docker/glances.yml"
    - include: "docker/portainer_agent.yml"
    - include: "docker/hass.yml"
    - include: "docker/deconz.yml"
    - include: "docker/cups.yml"

- hosts: tvhead
  become: true
  vars:
    create_containers: 4
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1d

  tasks:
    - include: "docker/glances.yml"
    - include: "docker/portainer_agent.yml"
    - include: "docker/tvheadend.yml"
    - include: "docker/vnc.yml"
    - include: "docker/nextcloud.yml"
    - include: "docker/qbit.yml"
    - include: "docker/jellyfin.yml"
    - include: "docker/audiobookshelf.yml"