---
- hosts: all
  become: true
  vars:
    create_containers: 4
    default_container_name: docker
    default_container_image: ubuntu
    default_container_command: sleep 1d

  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'python3-docker', 'libffi-dev', 'podman']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: "deb {{ '[arch=arm64]' if ansible_architecture == 'aarch64' else '[arch=amd64]'  }} https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
        state: present
      ignore_errors: yes


    - name: Update apt and install docker-ce
      apt: update_cache=yes pkg={{item}} state=latest
      with_items: [docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin]


