---
- name: Install fail2ban
  hosts: mini
  become: yes
  tasks:
    - name: Ensures /etc/fail2ban/filter.d/ dir exists
      file: path=/etc/fail2ban/filter.d/ state=directory
    - name: Ensures /etc/fail2ban/action.d/ dir exists
      file: path=/etc/fail2ban/action.d/ state=directory
    - name: create filter.d template
      template:
        src: "{{ item }}"
        dest: /etc/fail2ban/filter.d/{{ item | basename }}
      with_fileglob:
      - templates/filter.d/*
    - name: create action.d template
      template:
        src: "{{ item }}"
        dest: /etc/fail2ban/action.d/{{ item | basename }}
      with_fileglob:
      - templates/filter.d/*
    - name: install fail2ban package
      apt: pkg=fail2ban state=present
    - name: copy fail2ban local config
      template: src=jail.local dest=/etc/fail2ban/jail.local owner=root group=root mode=0644
