---
# preload
- hosts:
    - mini
  become: yes
  gather_facts: False
  pre_tasks:
    - raw: test -e /usr/bin/python || test -e /usr/bin/python3 || (apt -y -qq update && DEBIAN_FRONTEND=noninteractive apt install -y -q --option \"Dpkg::Options::=--force-confold\" python3-minimal)

- name: Install custom packages on mini
  hosts: mini
  become: yes
  tasks:
    - name: Update and install glances
      apt: pkg={{item}} state=present
      with_items: [glances]
    - name: Change the startup switch from false to true
      command: sudo sed -i 's/false/true/g' /etc/default/glances
    - name: create service
      template: src=glances.service dest=/lib/systemd/system/glances.service owner=root group=root mode=0644
    - name: Reload systemd
      command: sudo systemctl daemon-reload
    - name: Enable glances service
      command: sudo systemctl enable glances.service    
    - name: Start glances service
      command: sudo systemctl restart glances.service