# This is the main playbook 
# ansible-playbook main-playbook.yml

---
- name: Check file preexistance
  hosts: mini
  user: root
  tasks:
    - name: "Check htpassw"
      stat: path=/etc/nginx/passwords/iu_pa.password
      register: htpass_file
- name: Install passwords on mini
  hosts: mini
  user: root
  tasks:
    - name: "Request input username"
      pause:
        prompt: "htpassw username?" 
      register: htpass_username
      when: htpass_file.stat.exists == False
    - name: "Request input password"
      pause:
        prompt: "htpassw password"
      register: htpass_password
      when: htpass_file.stat.exists == False
    - name: "Request input password confirmation"
      pause:
        prompt: "Repeat htpassw password?"
      register: htpass_ask_twice
      when: htpass_file.stat.exists == False
    - name: Make sure password match for htpassw
      fail:
        msg: "Htpwd Password Mismatch"
      when: htpass_file.stat.exists == False and htpass_password.user_input != htpass_ask_twice.user_input
    - name: Make sure we can use htpasswd module
      apt: "pkg=python-passlib state=installed"
      when: htpass_file.stat.exists == False
    - name: "Generate htpasswd"
      htpasswd:
        path: /etc/nginx/passwords/iu_pa.password
        name: "{{ htpass_username.user_input }}"
        password: "{{ htpass_password.user_input }}"
        owner: root
        group: www-data
        mode: 0640
      when: htpass_file.stat.exists == False
- name: Install jdauphant.nginx on mini
  hosts: mini
  user: root
  roles:
    - jdauphant.ssl-certs
    - role: jdauphant.nginx
      nginx_configs:
          ssl:
               - ssl_certificate_key {{ssl_certs_privkey_path}}
               - ssl_certificate     {{ssl_certs_cert_path}}
      nginx_sites:
          default:
               - listen 443 ssl
               - server_name _
               - root "/var/www/html"
               - index index.html
               - |
                 location / {
                     # First attempt to serve request as file, then
                     # as directory, then fall back to displaying a 404.
                     try_files $uri $uri/ =404;
                 }
               - |
                 location /qbittorrent/ {
                     proxy_pass         http://127.0.0.1:8080/;
                     auth_basic           "qbittorrent";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                 }
               - |
                 location /transmission/ {
                     proxy_pass         http://127.0.0.1:9091/transmission/;
                     proxy_pass_header X-Transmission-Session-Id;
                     auth_basic           "transmission";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                 }
               - |
                 location /rpc {
                     proxy_pass         http://127.0.0.1:9091/transmission/rpc;
                 }
               - |
                 location /pub {
                     autoindex on;
                     auth_basic "Public";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                 }



