
---
- name: Install passwords on mini
  hosts: mini
  become: yes
  tasks:
    - include: tasks/request_credential.yml path_to_check=/etc/nginx/passwords/iu_pa.password
    - name: Make sure we can use htpasswd module
      apt: "pkg=python-passlib state=installed"
      when: file.stat.exists == False
    - name: "Generate htpasswd"
      htpasswd:
        path: /etc/nginx/passwords/iu_pa.password
        name: "{{ username.user_input }}"
        password: "{{ password.user_input }}"
        owner: root
        group: www-data
        mode: 0640
      when: file.stat.exists == False
- name: Install jdauphant.nginx on mini
  hosts: mini
  become: yes
  tasks:
    - name: copy /etc/nginx/conf.d/websocket.conf local config
      template: src=websocket.conf dest=/etc/nginx/conf.d/websocket.conf owner=root group=root mode=0644
    - name: copy /etc/nginx/conf.d/proxy_add_forwarded.conf local config
      template: src=proxy_add_forwarded.conf dest=/etc/nginx/conf.d/proxy_add_forwarded.conf owner=root group=root mode=0644
    - include: "{{ item }}"
      with_fileglob:
        - nginx/www/*.yml
  roles:
    - jdauphant.ssl-certs
    - role: jdauphant.nginx
      nginx_configs:
          ssl:
               - ssl_certificate_key {{ssl_certs_privkey_path}}
               - ssl_certificate     {{ssl_certs_cert_path}}
      nginx_sites:
          default:
               - listen 80
               - listen 8443 ssl
               - server_name netpascal.myvnc.com _
               - root "/var/www/html"
               - index index.html
               - |
                 location / {
                     # First attempt to serve request as file, then
                     # as directory, then fall back to displaying a 404.
                     auth_basic           "index";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                     try_files $uri $uri/ =404;
                 }
               - |
                 location /qbittorrent/ {
                     proxy_set_header X-Forwarded-Host $host:$server_port;
                     proxy_set_header X-Forwarded-Server $host;
                     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                     proxy_set_header Referer "";
                     proxy_set_header Origin "";
                     add_header x-frame-options "sameorigin";
                     proxy_hide_header Referer;
                     proxy_hide_header Origin;

                     proxy_pass         http://127.0.0.1:8080/;
                     auth_basic           "qbittorrent";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                 }
               - |
                 location /jenkins/ {
                      auth_basic           "jenkins";
                      auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                      proxy_set_header        Host $host:$server_port;
                      proxy_set_header        Port $server_port;
                      proxy_set_header        X-Real-IP $remote_addr;
                      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header        X-Forwarded-Proto $scheme; 
                      proxy_set_header        X-Forwarded-Port "443"; 
                      proxy_pass  http://127.0.0.1:8081/;                     
                 }
               - |
                 location /jenkins/hook/ {
                      # secured only by job uid
                      proxy_pass  http://127.0.0.1:8081/hook/;
                 }
               - |
                 location /transmission/ {
                     proxy_pass         http://127.0.0.1:9091/transmission/;
                     proxy_pass_header X-Transmission-Session-Id;
                     auth_basic           "transmission";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                 }
               - |
                 location /rpc {
                     proxy_pass         http://127.0.0.1:9091/transmission/rpc;
                 }
               - |
                 location /rssfeed/ {
                     proxy_pass         http://127.0.0.1:3355/rssfeed/;
                 }
               - |
                 location /rssme/ {
                     proxy_pass         http://127.0.0.1:3000/;
                 }
               - |
                 location /esphome/ {
                    proxy_pass         http://127.0.0.1:6052/;
                    proxy_set_header   Host              $host;
                    proxy_set_header   X-Real-IP         $remote_addr;
                    proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
                    proxy_set_header   X-Forwarded-Proto $scheme;
                    proxy_set_header   Upgrade           $http_upgrade;
                    proxy_set_header   Connection        "upgrade"; 
                    proxy_set_header   Origin            "";
                    proxy_hide_header  Origin;
                    auth_basic         "esphome"; 
                    auth_basic_user_file /etc/nginx/passwords/iu_pa.password;  
                 }
               - |
                 location /gate/ {
                    auth_basic           "gate";
                    auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                    proxy_pass         https://127.0.0.1:8000/gate/;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";
                    proxy_read_timeout 86400;
                    proxy_set_header Authorization $http_authorization;
                    proxy_set_header X-Forwarded-User $remote_user;
                    proxy_pass_header  Authorization;

                 }
               - |
                 location /podcast {
                     rewrite /podcast(.*) $1 break;

                     auth_basic           "podcast";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
      
                     include uwsgi_params;
                     uwsgi_pass 127.0.0.1:3031;
                     uwsgi_param X-Forwarded-Host $host/podcast;
                     uwsgi_param DOCUMENT_ROOT /pub/;
                     uwsgi_param X-Forwarded-Proto $scheme;

                 }
               - |
                 location /portainer/ {
                     proxy_pass         http://127.0.0.1:9000/;
                     auth_basic           "portainer";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;

                 }
               - |
                 location /pub {
                     autoindex on;
                     auth_basic "Public";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                 }
          home-assistant:
               - listen 80
               - listen 8443 ssl
               - server_name netpascal-home.myvnc.com home-assistant.pascallbqshfhm2o.onion home-assistant.5.51.46.163.xip.io
               - |
                 location / {
                     proxy_pass         http://127.0.0.1:8123;
                     proxy_set_header Host $host;
                     proxy_redirect http:// https://;
                     proxy_http_version 1.1;
                     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                     proxy_set_header Upgrade $http_upgrade;
                     proxy_set_header Connection $connection_upgrade;
             
                 }
