
---
- name: Install passwords on mini
  hosts: mini
  become: yes
  tasks:
    - include: tasks/request_credential.yml path_to_check=/etc/nginx/passwords/iu_pa.password
    - name: Make sure we can use htpasswd module
      apt: "pkg=python3-passlib state=present"
      when: file.stat.exists == False
    - name: "Generate htpasswd"
      htpasswd:
        path: /etc/nginx/passwords/iu_pa.password
        name: "{{ username.user_input }}"
        password: "{{ password.user_input }}"
        owner: root
        group: www-data
        mode: 0640
      when: file.stat.exists == False
    - name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
      include_vars: "{{ lookup('first_found', possible_files, errors='ignore') }}"
      vars:
        possible_files:
          - "vars/{{ ansible_lsb.id }}.yml"
      ignore_errors: yes
- name: Install packages to compile nginx
  hosts: mini
  become: yes
  tasks:
    - name: install packages
      apt: pkg={{item}} state=present
      with_items: [libz-dev]


- name: Install modsec3.nginx on mini
  hosts: mini
  become: yes
  tasks:
    - name: Install required packages to compile modsec3-crs3
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'zlib1g-dev']
  roles:
    - role: ansible-role-nginx-modsec3-crs3
      nginx_pkgs:
        - nginx
      nginx_install_epel_repo: False
      nginx_official_repo: True
      nginx_official_repo_mainline: True
      nginx_module_configs:
        - ngx_http_modsecurity_module
      nginx_modules_location: /usr/lib/nginx/modules
      nginx_sites:
          default:
               - listen 80
               - server_name _
               - server_tokens off
               - location / { return 302 https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=DNXMX4C5MFAZC&source=url; }


- name: Install custom nginx config on mini
  hosts: mini
  become: yes
  tasks:
    - name: Ensures /etc/nginx/conf.d/ dir exists
      file: path=/etc/nginx/conf.d/ state=directory
    - name: Ensures /etc/nginx/site-enabled/ dir exists
      file: path=/etc/nginx/site-enabled/ state=directory
    - name: Ensures /etc/nginx/site-available/ dir exists
      file: path=/etc/nginx/site-available/ state=directory
    - name: Ensures /etc/nginx/modules-enabled/ dir exists
      file: path=/etc/nginx/modules-enabled/ state=directory
    - name: create conf.d template
      template:
        src: "{{ item }}"
        dest: /etc/nginx/conf.d/{{ item | basename }}
      with_fileglob:
      - templates/conf.d/*
    - name: create available vhost template
      template:
        src: "{{ item }}"
        dest: /etc/nginx/site-available/{{ item | basename }}
      with_fileglob:
      - templates/vhost/*
    - name: Apply symlinks in sites-enabled
      file:
        dest: /etc/nginx/sites-enabled/{{ item }}
        src: /etc/nginx/site-available/{{ item }}
        state: link
        force: yes
      with_items:
      - bitwardenrs.conf
      - cachet.conf
      - evernote.conf
      - grocy.conf
      - home-assistant.conf
      - jellyfin.conf
      - mkdocs.conf
      - nextcloud.conf
      - node-red.conf
      - photoprism.conf
      - qbitorrent.conf 
      - redmine.conf
      - registry.conf
      - rssfeed.conf
      - tvheadend.conf
      - wishlist.conf
    - name: create nginx modules template
      template:
        src: "{{ item }}"
        dest: /etc/nginx/modules-enabled/{{ item | basename }}
      with_fileglob:
      - templates/modules.d/*
    - name: Disable modsec 404 for fail2ban
      replace:
        path: "/etc/nginx/modsec/modsecurity.conf"
        regexp: "SecAuditLogRelevantStatus"
        replace: "#SecAuditLogRelevantStatus"
    - name: Handle nginx modsecurity bug due to out of memory issue
      replace:
        path: "/lib/systemd/system/nginx.service"
        regexp: "KillMode=mixed"
        replace: "KillMode=mixed\nRestart=on-failure\nRestartSec=900s"
    - name: Restart nginx for update modsec 404 for fail2ban
      command: service nginx restart

- name: Log rotate custom logs
  hosts: mini
  become: yes
  tags: nginx-post-install
  tasks:
    - name: Ensures /etc/logrotate.d/ dir exists
      file: path=/etc/logrotate.d/ state=directory
    - name: create logrotate rule
      template:
        src: "{{ item }}"
        dest: /etc/logrotate.d/{{ item | basename }}
      with_fileglob:
      - templates/logrotate.d/*
