
---
- name: Install passwords on mini
  hosts: mini
  become: yes
  tasks:
    - include: tasks/request_credential.yml path_to_check=/etc/nginx/passwords/iu_pa.password
    - name: Make sure we can use htpasswd module
      apt: "pkg=python-passlib state=installed"
      when: file.stat.exists == False
    - name: "Generate htpasswd"
      htpasswd:
        path: /etc/nginx/passwords/iu_pa.password
        name: "{{ username.user_input }}"
        password: "{{ password.user_input }}"
        owner: root
        group: www-data
        mode: 0640
      when: file.stat.exists == False
    - name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
      include_vars: "{{ lookup('first_found', possible_files, errors='ignore') }}"
      vars:
        possible_files:
          - "vars/{{ ansible_lsb.id }}.yml"
      ignore_errors: yes

- name: Install jdauphant.nginx on mini
  hosts: mini
  become: yes
  tasks:
    - name: Ensures /etc/nginx/conf.d/ dir exists
      file: path=/etc/nginx/conf.d/ state=directory
    - name: copy /etc/nginx/conf.d/websocket.conf local config
      template: src=websocket.conf dest=/etc/nginx/conf.d/websocket.conf owner=root group=root mode=0644
    - name: copy /etc/nginx/conf.d/proxy_add_forwarded.conf local config
      template: src=proxy_add_forwarded.conf dest=/etc/nginx/conf.d/proxy_add_forwarded.conf owner=root group=root mode=0644
    - name: Ensures /etc/nginx/site-enabled/ dir exists
      file: path=/etc/nginx/site-enabled/ state=directory
    - name: create vhost template
      template:
        src: "{{ item }}"
        dest: /etc/nginx/site-enabled/{{ item | basename | regex_replace('\.j2$', '') }}
      with_fileglob:
      - ../templates/vhost/*
  roles:
    - jdauphant.ssl-certs
    - role: jdauphant.nginx
      nginx_configs:
          ssl:
               - ssl_certificate_key {{ssl_certs_privkey_path}}
               - ssl_certificate     {{ssl_certs_cert_path}}
      nginx_sites:
          default:
               - listen 80
               - listen 8443 ssl
               - server_name netpascal.myvnc.com _
               - root "/var/www/html"
               - index index.html
               - |
                 location / {
                     auth_basic           "index";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                     proxy_set_header        Host $host;
                     proxy_set_header        X-Forwarded-Proto "https";
                     proxy_pass http://127.0.0.1:16374;
                 }
               - |
                 location ~ /netdata/(?<ndpath>.*) {
                     auth_basic           "netdata";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                     proxy_redirect off;
                     proxy_set_header Host $host;

                     proxy_set_header X-Forwarded-Host $host;
                     proxy_set_header X-Forwarded-Server $host;
                     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                     proxy_http_version 1.1;
                     proxy_pass_request_headers on;
                     proxy_set_header Connection "keep-alive";
                     proxy_store off;
                     proxy_pass http://127.0.0.1:19999/$ndpath$is_args$args;

                     gzip on;
                     gzip_proxied any;
                     gzip_types *;

                 }
               - |
                 location ^~ /nextcloud/ {
                     proxy_pass http://127.0.0.1:9003/;
                     rewrite /nextcloud(.*) $1 break;
                     proxy_max_temp_file_size 2048m;
                     proxy_headers_hash_max_size 512;
                     proxy_headers_hash_bucket_size 64;
                     proxy_set_header Host $host;
                     proxy_set_header X-Forwarded-Proto $scheme;
                     proxy_set_header X-Real-IP $remote_addr;
                     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                     add_header Front-End-Https on;
                     proxy_set_header Range $http_range;
                     proxy_set_header If-Range $http_if_range;
                     proxy_set_header Connection $http_connection;
                     proxy_redirect off;
                     proxy_ssl_session_reuse off;
                 }
               - |
                 location /qbittorrent/ {
                     proxy_set_header X-Forwarded-Host $host:$server_port;
                     proxy_set_header X-Forwarded-Server $host;
                     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                     proxy_set_header Referer "";
                     proxy_set_header Origin "";
                     add_header x-frame-options "sameorigin";
                     proxy_hide_header Referer;
                     proxy_hide_header Origin;

                     proxy_pass         http://127.0.0.1:8080/;
                     auth_basic           "qbittorrent";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                 }
               - |
                 location /jenkins/ {
                      auth_basic           "jenkins";
                      auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                      proxy_set_header        Host $host:$server_port;
                      proxy_set_header        Port $server_port;
                      proxy_set_header        X-Real-IP $remote_addr;
                      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header        X-Forwarded-Proto $scheme; 
                      proxy_set_header        X-Forwarded-Port "443"; 
                      proxy_pass  http://127.0.0.1:8081/;                     
                 }
               - |
                 location /jenkins/hook/ {
                      # secured only by job uid
                      proxy_pass  http://127.0.0.1:8081/hook/;
                 }
               - |
                 location /transmission/ {
                     proxy_pass         http://127.0.0.1:9091/transmission/;
                     proxy_pass_header X-Transmission-Session-Id;
                     auth_basic           "transmission";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                 }
               - |
                 location /rpc {
                     proxy_pass         http://127.0.0.1:9091/transmission/rpc;
                 }
               - |
                 location /rssfeed/ {
                     proxy_pass         http://127.0.0.1:3355/rssfeed/;
                 }
               - |
                 location /git/ {
                     auth_basic           "git";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                     proxy_pass         http://127.0.0.1:10080/;
                 }
               - |
                 location /joplin/ {
                     proxy_pass http://localhost:41185/joplin/;
                     auth_basic           "joplin";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                 }
               - |
                 location /vscode/ {
                     auth_basic           "vscode";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                     proxy_pass http://127.0.0.1:38311/;
                     proxy_http_version 1.1;
                     proxy_set_header Upgrade $http_upgrade;
                     proxy_set_header Connection "upgrade";
                     proxy_read_timeout 86400;
                 }
               - |
                 location /rssme/ {
                     proxy_pass         http://127.0.0.1:3000/;
                 }
               - |
                 location /esphome/ {
                    proxy_pass         http://127.0.0.1:6052/;
                    proxy_set_header   Host              $host;
                    proxy_set_header   X-Real-IP         $remote_addr;
                    proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
                    proxy_set_header   X-Forwarded-Proto $scheme;
                    proxy_set_header   Upgrade           $http_upgrade;
                    proxy_set_header   Connection        "upgrade"; 
                    proxy_set_header   Origin            "";
                    proxy_hide_header  Origin;
                    auth_basic         "esphome"; 
                    auth_basic_user_file /etc/nginx/passwords/iu_pa.password;  
                 }
               - |
                 location /gate/ {
                    auth_basic           "gate";
                    auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                    proxy_pass         https://127.0.0.1:8000/gate/;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";
                    proxy_read_timeout 86400;
                    proxy_set_header Authorization $http_authorization;
                    proxy_set_header X-Forwarded-User $remote_user;
                    proxy_pass_header  Authorization;

                 }
               - |
                 location /podcast {
                     rewrite /podcast(.*) $1 break;

                     auth_basic           "podcast";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
      
                     include uwsgi_params;
                     uwsgi_pass 127.0.0.1:3031;
                     uwsgi_param X-Forwarded-Host $host/podcast;
                     uwsgi_param DOCUMENT_ROOT /pub/;
                     uwsgi_param X-Forwarded-Proto $scheme;

                 }
               - |
                 location /pub {
                     autoindex on;
                     auth_basic "Public";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                 }
