
---
- name: Install passwords on mini
  hosts: mini
  become: yes
  tasks:
    - include: tasks/request_credential.yml path_to_check=/etc/nginx/passwords/iu_pa.password
    - name: Make sure we can use htpasswd module
      apt: "pkg=python3-passlib state=present"
      when: file.stat.exists == False
    - name: "Generate htpasswd"
      htpasswd:
        path: /etc/nginx/passwords/iu_pa.password
        name: "{{ username.user_input }}"
        password: "{{ password.user_input }}"
        owner: root
        group: www-data
        mode: 0640
      when: file.stat.exists == False
    - name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
      include_vars: "{{ lookup('first_found', possible_files, errors='ignore') }}"
      vars:
        possible_files:
          - "vars/{{ ansible_lsb.id }}.yml"
      ignore_errors: yes

- name: Install jdauphant.nginx on mini
  hosts: mini
  become: yes
  tasks:
    - name: Ensures /etc/nginx/conf.d/ dir exists
      file: path=/etc/nginx/conf.d/ state=directory
    - name: Ensures /etc/nginx/site-enabled/ dir exists
      file: path=/etc/nginx/site-enabled/ state=directory
    - name: create conf.d template
      template:
        src: "{{ item }}"
        dest: /etc/nginx/conf.d/{{ item | basename }}
      with_fileglob:
      - templates/conf.d/*
    - name: create vhost template
      template:
        src: "{{ item }}"
        dest: /etc/nginx/sites-enabled/{{ item | basename }}
      with_fileglob:
      - templates/vhost/*
  roles:
    - role: jdauphant.nginx
      nginx_sites:
          default:
               - listen 80
               - listen 8443 ssl
               - listen [::]:443 ssl http2
               - server_name _
               - server_tokens off
               - location / { return 302 https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=DNXMX4C5MFAZC&source=url; }


