
---
- name: Install passwords on mini
  hosts: mini
  become: yes
  tasks:
    - include: tasks/request_credential.yml path_to_check=/etc/nginx/passwords/iu_pa.password
    - name: Make sure we can use htpasswd module
      apt: "pkg=python-passlib state=installed"
      when: file.stat.exists == False
    - name: "Generate htpasswd"
      htpasswd:
        path: /etc/nginx/passwords/iu_pa.password
        name: "{{ username.user_input }}"
        password: "{{ password.user_input }}"
        owner: root
        group: www-data
        mode: 0640
      when: file.stat.exists == False
    - name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
      include_vars: "{{ lookup('first_found', possible_files, errors='ignore') }}"
      vars:
        possible_files:
          - "vars/{{ ansible_lsb.id }}.yml"
      ignore_errors: yes

- name: Install jdauphant.nginx on mini
  hosts: mini
  become: yes
  tasks:
    - name: Ensures /etc/nginx/conf.d/ dir exists
      file: path=/etc/nginx/conf.d/ state=directory
    - name: Ensures /etc/nginx/site-enabled/ dir exists
      file: path=/etc/nginx/site-enabled/ state=directory
    - name: create conf.d template
      template:
        src: "{{ item }}"
        dest: /etc/nginx/conf.d/{{ item }}
      with_fileglob:
      - ../templates/conf.d/*
    - name: create vhost template
      template:
        src: "{{ item }}"
        dest: /etc/nginx/site-enabled/{{ item }}
      with_fileglob:
      - ../templates/vhost/*
  roles:
    - role: jdauphant.nginx
      nginx_sites:
          default:
               - listen 80
               - listen 8443 ssl
               - server_name netpascal.myvnc.com _
               - root "/var/www/html"
               - index index.html
               - |
                 location / {
                     auth_basic           "index";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                     proxy_set_header        Host $host;
                     proxy_set_header        X-Forwarded-Proto "https";
                     proxy_pass http://127.0.0.1:16374;
                 }
               - |
                 location /qbittorrent/ {
                     proxy_set_header X-Forwarded-Host $host:$server_port;
                     proxy_set_header X-Forwarded-Server $host;
                     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                     proxy_set_header Referer "";
                     proxy_set_header Origin "";
                     add_header x-frame-options "sameorigin";
                     proxy_hide_header Referer;
                     proxy_hide_header Origin;

                     proxy_pass         http://127.0.0.1:8080/;
                     auth_basic           "qbittorrent";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                 }
               - |
                 location /jenkins/ {
                      auth_basic           "jenkins";
                      auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                      proxy_set_header        Host $host:$server_port;
                      proxy_set_header        Port $server_port;
                      proxy_set_header        X-Real-IP $remote_addr;
                      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header        X-Forwarded-Proto $scheme; 
                      proxy_set_header        X-Forwarded-Port "443"; 
                      proxy_pass  http://127.0.0.1:8081/;                     
                 }
               - |
                 location /jenkins/hook/ {
                      # secured only by job uid
                      proxy_pass  http://127.0.0.1:8081/hook/;
                 }
               - |
                 location /transmission/ {
                     proxy_pass         http://127.0.0.1:9091/transmission/;
                     proxy_pass_header X-Transmission-Session-Id;
                     auth_basic           "transmission";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                 }
               - |
                 location /rpc {
                     proxy_pass         http://127.0.0.1:9091/transmission/rpc;
                 }
               - |
                 location /rssfeed/ {
                     proxy_pass         http://127.0.0.1:3355/rssfeed/;
                 }
               - |
                 location /git/ {
                     auth_basic           "git";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                     proxy_pass         http://127.0.0.1:10080/;
                 }
               - |
                 location /joplin/ {
                     proxy_pass http://localhost:41185/joplin/;
                     auth_basic           "joplin";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                 }
               - |
                 location /rssme/ {
                     proxy_pass         http://127.0.0.1:3000/;
                 }
               - |
                 location /pub {
                     autoindex on;
                     auth_basic "Public";
                     auth_basic_user_file /etc/nginx/passwords/iu_pa.password;
                 }
