---
- name: Prepare install passwords on mini
  hosts: mini
  become: yes
  tasks:
    - include: tasks/request_credential.yml path_to_check=/var/lib/samba/private/passdb.tdb
    - name: Add the user with a bash shell
      ansible.builtin.user:
        name: "{{ username.user_input }}"
        password: "{{ password.user_input }}"
        shell: /bin/bash
- name: Install samba on mini
  hosts: mini
  become: yes
  roles:
    - role: bertvv.samba
      samba_users:
        - name: "{{ username.user_input }}"
          password: "{{ password.user_input }}"
      samba_shares:
        - name: usbs
          comment: "Mounted Media Directories"
          path: /media/
          valid_users: "{{ username.user_input }}"
      samba_global_include: samba-extra.conf
      when: file.stat.exists == False
