---
- name: Prepare install passwords on mini
  hosts: mini
  become: yes
  tasks:
    - include: tasks/request_credential.yml path_to_check=/var/lib/samba/private/passdb.tdb

- name: Install samba on mini
  hosts: mini
  become: yes
  roles:
    - role: bertvv.samba
      samba_users:
        - name: "{{ username.user_input }}"
          password: "{{ password.user_input }}"
      samba_shares:
        - name: usbs
          comment: "Mounted Media Directories"
          path: /media/
          valid_users: "{{ username.user_input }}"
      when: file.stat.exists == False
