---
- name: Install vnc on mini
  hosts: mini
  become: yes
  tasks:
    - name: install x11vnc
      apt: pkg=x11vnc state=present
    - name: Creates directory
      file: path=/etc/vnc state=directory
    - include: tasks/request_credential.yml path_to_check=/etc/vnc/passwd
    - name: generate x11vnc password file
      shell: x11vnc -storepasswd {{ password.user_input }}  /etc/vnc/passwd
      when: file.stat.exists == False
    - name: autostart x11vnc
      template: src=x11vnc-autostart.desktop dest=/etc/xdg/autostart/x11vnc-autostart.desktop owner=pascal group=pascal mode=0664
